version: "3"
services:
  sauerbraten:
    image: ghcr.io/arnoschutijzer/sauerbraten.docker:master
    # build: .
    restart: always
    platform: linux/amd64
    networks:
      - sauernet
    ports:
      - "28785:28785/tcp"
      - "28785:28785/udp"
      - "28786:28786/tcp"
      - "28786:28786/udp"

networks:
  sauernet:
